
# POST http://localhost:4004/odata/v4/mini-mart/PLANT_INFO
# Content-Type: application/json

# {
#       "PLANT_ID": "t1",
#       "PLANT_NAME": "Pune"
# }

# GET http://localhost:4004/odata/v4/mini-mart/CUSTOMERS_INFO

# POST http://localhost:4004/odata/v4/mini-mart/CUSTOMERS_INFO
# Content-Type: application/json

# {
#       "CUSTOMER_ID": "1",
#       "CUSTOMER_NAME": "John",
#       "CUSTOMER_EMAILID": "John@gmail.com",
#       "CUSTOMER_CONTACTNO": "123456789",
#       "CUSTOMER_lOCATION": "Pune"
# }

# POST http://localhost:4004/odata/v4/mini-mart/CUSTOMERS_INFO
# Content-Type: application/json

# {
#       "CUSTOMER_ID": "2",
#       "CUSTOMER_NAME": "Harry",
#       "CUSTOMER_EMAILID": "Harry@gmail.com",
#       "CUSTOMER_CONTACTNO": "8736468389",
#       "CUSTOMER_lOCATION": "Hyderabad"
# }


# POST http://localhost:4004/odata/v4/mini-mart/EMPLOYEES_INFO
# Content-Type: application/json

# {
    
#       "EMPLOYEE_ID": "720",
#       "EMPLOYEE_NAME": "",
#       "EMPLOYEE_EMAILID": "John@gmail.com",
#       "EMPLOYEE_CONTACTNO": "123456789",
#       "EMPLOYEE_lOCATION": "Pune",
#       "EMPLOYEE_DESIGNATION": "Software Developer",
#       "EMPLOYEE_PLANT_LOCATION": "Pune"
# }

# PUT http://localhost:4004/odata/v4/mini-mart/CUSTOMERS_INFO/1
# Content-Type: application/json

# {
#       "CUSTOMER_ID": "1",
#       "CUSTOMER_CONTACTNO": "423466789",
#       "CUSTOMER_lOCATION": "Mumbai",
#       "CUSTOMER_NAME": "John",
#       "CUSTOMER_EMAILID": "John@gmail.com",
#       "CUSTOMER_PLANT_LOCATION" : "Pune"
     
# }

# GET http://localhost:4004/odata/v4/mini-mart/PostVaildationArrays
# Content-Type: application/json


# GET http://localhost:4004/odata/v4/mini-mart/CallViews?Flag=P
# Content-Type: application/json

# GET http://localhost:4004/odata/v4/mini-mart/CallViewsForPlants?Flag=P
# Content-Type: application/json


# GET http://localhost:4004/odata/v4/mini-mart/CallViewsForCustomer?Flag=C
# Content-Type: application/json

# {
    
     
#       "EMPLOYEE_NAME": "Joy",
#       "EMPLOYEE_EMAILID": "Joy@gmail.com",
#       "EMPLOYEE_CONTACTNO": "127856789",
#       "EMPLOYEE_lOCATION": "Mumbai",
#       "EMPLOYEE_DESIGNATION": "Software Developer",
#       "EMPLOYEE_PLANT_LOCATION": "Pune"
# }

POST   http://localhost:4004/odata/v4/mini-mart/RunJob
Content-Type: application/json

{
  "Customers":[
{
      "CUSTOMER_ID": "A21",
      "CUSTOMER_CONTACTNO": "423466789",
      "CUSTOMER_lOCATION": "Mumbai",
      "CUSTOMER_NAME": "John",
      "CUSTOMER_EMAILID": "John@gmail.com",
      "CUSTOMER_PLANT_LOCATION" : "Pune"
     
},
{
      "CUSTOMER_ID": "A89",
      "CUSTOMER_CONTACTNO": "423466789",
      "CUSTOMER_lOCATION": "Mumbai",
      "CUSTOMER_NAME": "John",
      "CUSTOMER_EMAILID": "John@gmail.com",
      "CUSTOMER_PLANT_LOCATION" : "Pune"
     
},
{
      "CUSTOMER_ID": "A151",
      "CUSTOMER_CONTACTNO": "423466789",
      "CUSTOMER_lOCATION": "Mumbai",
      "CUSTOMER_NAME": "John",
      "CUSTOMER_EMAILID": "John@gmail.com",
      "CUSTOMER_PLANT_LOCATION" : "Pune"
     
},
{
      "CUSTOMER_ID": "A229",
      "CUSTOMER_CONTACTNO": "423466789",
      "CUSTOMER_lOCATION": "Mumbai",
      "CUSTOMER_NAME": "John",
      "CUSTOMER_EMAILID": "John@gmail.com",
      "CUSTOMER_PLANT_LOCATION" : "Pune"
     
}
  ]
}


# # POST   http://localhost:4004/odata/v4/mini-mart/RunJobEmployee
# Content-Type: application/json

# {
#     "Employees": [
#         {
#         "EMPLOYEE_ID" : "6",
#         "EMPLOYEE_NAME": "hem",
#         "EMPLOYEE_EMAILID": "hem@gmail.com",
#         "EMPLOYEE_CONTACTNO": "127856789",
#         "EMPLOYEE_lOCATION": "Mumbai",
#         "EMPLOYEE_DESIGNATION": "Software Developer",
#         "EMPLOYEE_PLANT_LOCATION": "Pune",
#         "EMPLOYEE_LIMIT": "40"
#         },
#           {
#         "EMPLOYEE_ID" : "2",
#         "EMPLOYEE_NAME": "hesm",
#         "EMPLOYEE_EMAILID": "hsem@gmail.com",
#         "EMPLOYEE_CONTACTNO": "127856789",
#         "EMPLOYEE_lOCATION": "Mumbai",
#         "EMPLOYEE_DESIGNATION": "Software Developer",
#         "EMPLOYEE_PLANT_LOCATION": "Pune",
#         "EMPLOYEE_LIMIT": "50"
#         },
#           {
#         "EMPLOYEE_ID" : "3",
#         "EMPLOYEE_NAME": "hesdm",
#         "EMPLOYEE_EMAILID": "hesdm@gmail.com",
#         "EMPLOYEE_CONTACTNO": "127856789",
#         "EMPLOYEE_lOCATION": "Mumbai",
#         "EMPLOYEE_DESIGNATION": "Software Developer",
#         "EMPLOYEE_PLANT_LOCATION": "Pune",
#         "EMPLOYEE_LIMIT": "60"
#         },
#         {
#         "EMPLOYEE_ID" : "4",
#         "EMPLOYEE_NAME": "hfem",
#         "EMPLOYEE_EMAILID": "hesm@gmail.com",
#         "EMPLOYEE_CONTACTNO": "127856789",
#         "EMPLOYEE_lOCATION": "Mumbai",
#         "EMPLOYEE_DESIGNATION": "Software Developer",
#         "EMPLOYEE_PLANT_LOCATION": "Pune",
#         "EMPLOYEE_LIMIT": "80"
#         }
#     ]
# }



# POST   http://localhost:4004/odata/v4/mini-mart/users_info
# Content-Type: application/json

# {
    
#     "USER_ID" : "14",
#         "USER_NAME" : "Harsha245",
#         "USER_EMAILID": "Harsha635@gmail.com",
#         "USER_CONTACTNO" : "9457648374",
#         "USER_PURCHASE" : "290"
# }

# PUT   http://localhost:4004/odata/v4/mini-mart/users_info/9
# Content-Type: application/json

# {
    
    
#         "USER_NAME" : "henry",
#         "USER_EMAILID": "henry@gmail.com",
#         "USER_CONTACTNO" : "9475648374",
#         "USER_PURCHASE" : "290"
# }

# DELETE    http://localhost:4004/odata/v4/mini-mart/users_info/9
# Content-Type: application/json
